version: '3'

services:
  pdfServ:
    image: jeleniep/node-pdf
    ports:
    - "8080:8080"
    

  web:
    image: jeleniep/flask-redis
    depends_on:
    - db
    volumes:
    - ./flask-redis:/var/www/app
    ports:
    - "5000:5000"

  db:
    image: redis